<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBK7CszD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBK7CszD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBK7CszD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBK7CszD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBK7CszD\App_KernelDevDebugContainer([
    'container.build_hash' => 'BK7CszD',
    'container.build_id' => '9570d9d9',
    'container.build_time' => 1710932485,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBK7CszD');
